### ISSUE TITLE
Sync issue status

### ISSUE THREAD

**Issue by yrodiere** [hibernate/replicate-jira#10]
See https://issues.redhat.com/browse/HHH-18747

Upstream status is "waiting for review". Downstream status is "New"; should be "In progress".

**Comment by marko-bekhta** [comment]
This one is on me 🙈 😭  I've placed the `Waiting for review` with all others like `Awaiting Contribution`/`Awaiting Response` statuses as `New`. Will move the review one to the in-progress group...

**Comment by yrodiere** [comment]
Thank @marko-bekhta . I just noticed the following issue is "New" downstream but "Closed" upstream, is this the same issue?

https://issues.redhat.com/browse/HSEARCH-3844
https://hibernate.atlassian.net/browse/HSEARCH-3844

**Comment by yrodiere** [comment]
> But since I've triggered it for other issues too (still running), just to be more sure that statuses match, we might see comments like https://issues.redhat.com/browse/HSEARCH-3844?focusedId=25931897&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25931897 repeat themselves.... The thing is that with the current workflow, the same transition to close the issue can be applied to a closed issue 😃 and we do not check the current status of the issue before trying to apply the transition (so that we do not make extra REST calls)...

I tend to think we can just... not add such comments, ever? I'm not sure they provide a lot of value.

If you think the upstream status matters, maybe just include it in the issue description. But I personally don't think it's very important.
