### ISSUE TITLE
Include name of downstream users in comments

### ISSUE THREAD

**Issue by yrodiere** [hibernate/replicate-jira#20]
We can't reasonably copy the name of all users when syncing comments -- the information is too sensitive.
So right now [this](https://hibernate.atlassian.net/browse/HSEARCH-3100?focusedCommentId=117033) is getting synced as:

> This [comment](https://hibernate.atlassian.net/browse/HSEARCH-3100?focusedCommentId=117033) was posted by the [user :58fa1ced-171a-4c00-97e8-5d70d442cc4b](https://hibernate.atlassian.net/jira/people/557058:58fa1ced-171a-4c00-97e8-5d70d442cc4b).
> 
> Please ignore – just testing webhooks.

BUT... for team members, it's actually legitimate and reasonable to display the name.

Maybe we could change the comment syncing so that the reference to the user actually points to the "downstream" user?

**Comment by marko-bekhta** [comment]
so something like for this comment ? https://hibernate.atlassian.net/browse/HSEARCH-5257?focusedCommentId=117035

If so, we probably can do the same for the description as well (we already have the assignee and reporter set, but if we update the comment then might as well do the same logic for description too)

**Comment by marko-bekhta** [comment]
ok, so it seems we can do that, yes 😄
