### ISSUE TITLE
Sync epic-specific data

### ISSUE THREAD

**Issue by yrodiere** [hibernate/replicate-jira#31]
In particular it would seem Epic "labels" are not synced:

![image](https://github.com/user-attachments/assets/e8bf7119-c43e-49e8-bab7-840ce5426dba)

See the "epics" panel on the left of https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=20313&view=planning.nodetail&epics=visible&issueLimit=100&selectedEpic=HBX-2390#

**Comment by marko-bekhta** [comment]
😖 it's convenient that these (epic label, link color and so on) are custom fields 🥲 and are different from instance to instance 😄 
but should be better now:
![image](https://github.com/user-attachments/assets/ae067de8-1663-4561-b698-6337adf3b987)
will deploy and re-sync orm/tools; search is already updated

**Comment by marko-bekhta** [comment]
this is a nice epic https://hibernate.atlassian.net/browse/HHH-15043 😖 
😆

**Comment by yrodiere** [comment]
Thanks, it works! Closing.

> this is a nice epic https://hibernate.atlassian.net/browse/HHH-15043 😖 😆

Indeed... I deleted it upstream, and archived/closed downstream. Related: https://github.com/hibernate/replicate-jira/issues/34
