### ISSUE TITLE
Include important date/times in descriptions of upstream actions/statuses

### ISSUE THREAD

**Issue by yrodiere** [hibernate/replicate-jira#45]
In particular:

* The creation/last update date in the issue description
* The closing date in the issue description
* The comment creation / last edit date in comments
* etc.

**Comment by marko-bekhta** [comment]
Tested it here https://issues.redhat.com/browse/HSEARCH-5082...  (see there's my comment that had an "edit")

Created/last updated are easy to add. As for the closed date 🤔... how valuable would it be?  Note that for issues that are synced by the tool through the hook, we'd see the transition in the ticket history. 
I could check that `new issue status != current issue status && new issue status == closed` but this would work only on the close transition. If someone edits the issue after that... we'd need to read the downstream description, get the value out of it (probably some regex 🥲) and then add that date to the "new description"...

**Comment by yrodiere** [comment]
> Created/last updated are easy to add.

Thanks!

> As for the closed date 🤔... how valuable would it be? Note that for issues that are synced by the tool through the hook, we'd see the transition in the ticket history.

Yeah it's mostly for the thousands of already-closed issues have been synced in the past few weeks: for those, Jira history is incorrect :/

>  I could check that new issue status != current issue status && new issue status == closed but this would work only on the close transition. If someone edits the issue after that... we'd need to read the downstream description, get the value out of it (probably some regex 🥲) and then add that date to the "new description"...

I though Jira stored the date somewhere... If not, never mind: we can always rely on the "fix version", which I see you sync as labels.
