### ISSUE TITLE
Issue links not getting synced

### ISSUE THREAD

**Issue by marko-bekhta** [hibernate/replicate-jira#77]
I've noticed a few logs as:
```
"POST /api/jira/webhooks/?triggeredByUser=bla-bla-bla HTTP/1.1" 404 53
"POST /api/jira/webhooks/?triggeredByUser=bla-bla-bla HTTP/1.1" 404 53
"POST /api/jira/webhooks/?triggeredByUser=bla-bla-bla HTTP/1.1" 404 53
"POST /api/jira/webhooks/?triggeredByUser=bla-bla-bla HTTP/1.1" 404 53
```

Where the project key is missing from the POST URL. And from what I've found so far: adding/updating issue links triggers that kind of event. My guess is that the webhook cannot figure out the `{{project.key}}` when triggering this, resulting in a missing project key 😕 

I guess we have two options:
- we either create a hook per project and hardcode the project key in the URL
- we update the app so that the project key is not required for the link events.

@yrodiere, which option would you prefer? 😃

**Comment by yrodiere** [comment]
I've always wondered why the project key needed to be part of the webhook, since it's most likely part of the request body...

I'd just resolve the project key from the request body as a fallback?
